"""Initial tables

Revision ID: f54a89f4b0c6
Revises: 
Create Date: 2026-06-23 13:07:37.043212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f54a89f4b0c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=False)
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=False)
    op.create_table('instructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('career_plot_file_id', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructors_career_plot_file_id'), 'instructors', ['career_plot_file_id'], unique=False)
    op.create_index(op.f('ix_instructors_id'), 'instructors', ['id'], unique=False)
    op.create_index(op.f('ix_instructors_name'), 'instructors', ['name'], unique=True)
    op.create_table('users',
    sa.Column('telegram_user_id', sa.BIGINT(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_subscribed', sa.BOOLEAN(), nullable=False),
    sa.Column('subscribed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_active_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_blocked', sa.BOOLEAN(), nullable=False),
    sa.Column('block_reason', sa.VARCHAR(length=255), nullable=True),
    sa.Column('blocked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('telegram_user_id')
    )
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BIGINT(), nullable=False),
    sa.Column('feedback_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('message_text', sa.VARCHAR(), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['users.telegram_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_telegram_user_id'), 'feedback', ['telegram_user_id'], unique=False)
    op.create_table('offerings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('academic_year', sa.VARCHAR(length=10), nullable=False),
    sa.Column('semester', sa.VARCHAR(length=10), nullable=False),
    sa.Column('total_registered', sa.Integer(), nullable=True),
    sa.Column('current_registered', sa.Integer(), nullable=True),
    sa.Column('total_drop', sa.Integer(), nullable=True),
    sa.Column('accepted_drop', sa.Integer(), nullable=True),
    sa.Column('plot_file_id', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['courses.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_code', 'academic_year', 'semester', name='uq_offering')
    )
    op.create_index(op.f('ix_offerings_academic_year'), 'offerings', ['academic_year'], unique=False)
    op.create_index(op.f('ix_offerings_course_code'), 'offerings', ['course_code'], unique=False)
    op.create_index(op.f('ix_offerings_id'), 'offerings', ['id'], unique=False)
    op.create_index(op.f('ix_offerings_plot_file_id'), 'offerings', ['plot_file_id'], unique=False)
    op.create_index(op.f('ix_offerings_semester'), 'offerings', ['semester'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('grade_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('count', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offering_id', 'grade_type', name='uq_grade')
    )
    op.create_index(op.f('ix_grades_id'), 'grades', ['id'], unique=False)
    op.create_index(op.f('ix_grades_offering_id'), 'grades', ['offering_id'], unique=False)
    op.create_table('offering_instructors',
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offering_id', 'instructor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offering_instructors')
    op.drop_index(op.f('ix_grades_offering_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_offerings_semester'), table_name='offerings')
    op.drop_index(op.f('ix_offerings_plot_file_id'), table_name='offerings')
    op.drop_index(op.f('ix_offerings_id'), table_name='offerings')
    op.drop_index(op.f('ix_offerings_course_code'), table_name='offerings')
    op.drop_index(op.f('ix_offerings_academic_year'), table_name='offerings')
    op.drop_table('offerings')
    op.drop_index(op.f('ix_feedback_telegram_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_instructors_name'), table_name='instructors')
    op.drop_index(op.f('ix_instructors_id'), table_name='instructors')
    op.drop_index(op.f('ix_instructors_career_plot_file_id'), table_name='instructors')
    op.drop_table('instructors')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
